import { Head, Link } from '@inertiajs/react';
import AppHeader from '../../components/AppHeader';
import { ReadOnlyBanner } from '../../components/Ui';
type Actor={display_name:string;roles:string[];capabilities:string[]};
type Summary={scope:string;candidate_profiles:number;profiles_fresh:number;profiles_stale:number;tracer_submitted:number;tracer_response_rate:number;jobs_active:number;jobs_expired:number;applications_total:number;applications_interview:number;applications_offer:number;hires_started:number;companies_active:number;event_participations:number;certificates_issued:number;employer_feedback_count:number};
const labels:Record<string,string>={candidate_profiles:'Profil alumni',profiles_fresh:'Profil segar',profiles_stale:'Perlu konfirmasi',tracer_response_rate:'Respons tracer (%)',jobs_active:'Lowongan aktif',jobs_expired:'Lowongan expired',applications_total:'Total lamaran',applications_interview:'Tahap interview',applications_offer:'Tahap offer',hires_started:'Mulai bekerja',companies_active:'Perusahaan aktif',event_participations:'Partisipasi event',certificates_issued:'Sertifikat',employer_feedback_count:'Employer feedback'};
export default function Overview({actor,summary}:{actor:Actor;summary:Summary}){
 const admin=actor.capabilities.includes('tracer.manage'); const viewer=actor.roles.includes('viewer-karir');
 return <><Head title="Dashboard Operasional"/><main className="admin-page app-surface"><AppHeader context="OPERASIONAL KARIER" home="/staff" nav={[{label:'Overview',href:'/staff',active:true},...(admin?[{label:'Tracer',href:'/admin/tracer'},{label:'Import Lowongan',href:'/admin/jobs/import'}]:[]),{label:'Talenta Internal',href:'/internal/talent'}]} logout/><section className="operational-shell"><header className="operational-hero"><div><p className="eyebrow">DASHBOARD AGREGAT</p><h1>Data untuk keputusan,<br/><em>privasi tetap terjaga.</em></h1><p>{summary.scope}. Angka ditampilkan sebagai agregat tanpa jawaban tracer, CV, kontak, atau dokumen kandidat.</p></div><span className="metric-orb">{summary.tracer_response_rate}%<small>respons tracer</small></span></header><div className="metric-grid">{Object.entries(labels).map(([key,label])=><article key={key}><small>{label}</small><strong>{summary[key as keyof Summary]}</strong><span>{key==='profiles_stale'?'perlu tindak lanjut':'data operasional'}</span></article>)}</div><div className="report-actions"><div><p className="eyebrow">EXPORT TERBATAS</p><h2>Unduh ringkasan operasional</h2><p>File hanya memuat metrik dalam scope assignment aktif.</p></div><div><a className="secondary-button" href="/staff/exports/csv">CSV</a><a className="primary-button" href="/staff/exports/xlsx">XLSX</a></div></div>{viewer&&<ReadOnlyBanner>Leadership menerima agregat sesuai assignment. Raw tracer, CV privat, credential, dan dokumen lamaran tidak disertakan.</ReadOnlyBanner>}<div className="operational-links">{admin&&<Link href="/admin/tracer">Kelola periode tracer →</Link>}{admin&&<Link href="/admin/jobs/import">Preview impor lowongan →</Link>}<Link href="/internal/talent">Direktori dalam scope →</Link></div></section></main></>;
}
