import { Head, router } from '@inertiajs/react';
import { CompanyHeader } from '../../../components/RoleHeader';
type Doc={id:number;type:string;name:string};
type Application={reference:string;candidate:string;headline:string|null;city:string|null;status:string;method:string;submitted_at:string|null;cover_letter:string|null;cv_snapshot:unknown;documents:Doc[];feedback_submitted:boolean};
export default function Applicants({job,applications}:{job:{reference:string;title:string};applications:Application[]}){
 const update=(reference:string,status:string)=>router.put('/company/jobs/'+job.reference+'/applicants/'+reference,{status});
 const feedback=(event:React.FormEvent<HTMLFormElement>,reference:string)=>{event.preventDefault();const form=new FormData(event.currentTarget);router.post('/company/applications/'+reference+'/feedback',{relationship:form.get('relationship'),ratings:{professionalism:Number(form.get('professionalism')),communication:Number(form.get('communication')),technical:Number(form.get('technical'))},strengths:form.get('strengths')});};
 return <><Head title={'Pelamar '+job.title}/><main className="job-page app-surface"><CompanyHeader context="MANAJEMEN PELAMAR" active="jobs" /><section className="job-shell"><header className="event-list-heading"><div><p className="eyebrow">PELAMAR LOWONGAN</p><h1>{job.title}</h1><p>Dokumen hanya dapat dibuka oleh kandidat, perusahaan pemilik lowongan, dan petugas berwenang.</p></div></header><div className="applicant-grid">{applications.map(item=><article key={item.reference}><div><small>{item.submitted_at} · {item.method}</small><h2>{item.candidate}</h2><p>{item.headline} · {item.city}</p></div>{item.cover_letter&&<blockquote>{item.cover_letter}</blockquote>}<div className="document-chips">{item.documents.map(doc=><a key={doc.id} href={'/company/applications/'+item.reference+'/documents/'+doc.id}>↗ {doc.type==='cover_letter'?'Cover Letter':doc.name}</a>)}</div><label>Status<select value={item.status} onChange={e=>update(item.reference,e.target.value)}><option value={item.status}>{item.status.replaceAll('_',' ')}</option><option value="under_review">under review</option><option value="assessment">assessment</option><option value="interview">interview</option><option value="offer">offer</option><option value="rejected">rejected</option><option value="hired_pending_start">hired pending start</option><option value="started">started</option></select></label><details><summary>Lihat snapshot CV terkunci</summary><pre>{JSON.stringify(item.cv_snapshot,null,2)}</pre></details><details className="feedback-panel"><summary>{item.feedback_submitted?'Perbarui masukan employer':'Beri masukan employer'}</summary><form onSubmit={e=>feedback(e,item.reference)}><label>Hubungan<select name="relationship"><option value="applicant">Pelamar</option><option value="interviewed">Sudah interview</option><option value="hired">Diterima</option><option value="started">Mulai bekerja</option></select></label><div className="form-split">{['professionalism','communication','technical'].map(key=><label key={key}>{key}<input name={key} type="number" min="1" max="5" defaultValue="4" required/></label>)}</div><label>Kekuatan<textarea name="strengths"/></label><button className="secondary-button">Simpan privat</button></form></details></article>)}</div>{!applications.length&&<div className="ds-empty-state"><span>◎</span><h2>Belum ada pelamar.</h2><p>Pelamar internal akan tampil setelah memilih dan mengirim CV.</p></div>}</section></main></>;
}
