import { Form, Head, router } from '@inertiajs/react';
import { useState } from 'react';
import { StaffHeader } from '../../../components/RoleHeader';
type Period={reference:string;title:string;cohort:string;program_reference:string|null;status:string;starts_on:string;ends_on:string;version:number|null;responses:number;total:number};
const starter=[{id:'employment_status',label:'Status kegiatan utama saat ini',type:'select',required:true,options:['Bekerja','Wirausaha','Studi lanjut','Belum bekerja','Belum diketahui']},{id:'employer_sector',label:'Sektor tempat bekerja',type:'text',required:false},{id:'waiting_months',label:'Masa tunggu kerja dalam bulan',type:'number',required:false},{id:'job_relevance',label:'Kesesuaian pekerjaan dengan bidang studi',type:'select',required:false,options:['Sangat sesuai','Sesuai','Kurang sesuai','Belum diketahui']}];
export default function Index({periods}:{periods:Period[]}){
 const [drafts,setDrafts]=useState<Record<string,string>>({});
 const publish=(reference:string)=>{try{router.post('/admin/tracer/periods/'+reference+'/versions',{questions:JSON.parse(drafts[reference]||JSON.stringify(starter))})}catch{alert('JSON pertanyaan belum valid.')}};
 return <><Head title="Tracer Operasional"/><main className="app-surface admin-page"><StaffHeader context="TRACER OPERASIONAL" active="tracer" /><section className="operational-shell"><header className="operational-hero"><div><p className="eyebrow">PERIODE & KUESIONER</p><h1>Tracer yang jujur,<br/><em>data yang tetap kontekstual.</em></h1><p>Setiap publikasi membuat versi baru. Respons lama tetap terikat pada pertanyaan saat dikirim.</p></div><span className="metric-orb">{periods.reduce((n,p)=>n+p.responses,0)}<small>respons masuk</small></span></header><div className="admin-two-column"><Form action="/admin/tracer/periods" method="post" className="panel-form"><h2>Buat periode</h2><label>Judul<input name="title" required/></label><label>Angkatan<input name="cohort" required placeholder="2022"/></label><label>Program<input name="program_reference" placeholder="S1 Farmasi"/></label><div className="form-split"><label>Mulai<input type="date" name="starts_on" required/></label><label>Selesai<input type="date" name="ends_on" required/></label></div><button className="primary-button">Simpan periode</button></Form><div className="period-list">{periods.map(period=><article key={period.reference}><div className="period-head"><div><small>{period.cohort} · {period.program_reference||'Semua program'}</small><h2>{period.title}</h2></div><span className={'status-chip '+period.status}>{period.status}</span></div><div className="mini-metrics"><span><b>{period.responses}</b> respons</span><span><b>v{period.version||'—'}</b> versi</span><span>{period.starts_on}—{period.ends_on}</span></div><details><summary>Publikasikan versi baru</summary><textarea value={drafts[period.reference]||JSON.stringify(starter,null,2)} onChange={e=>setDrafts({...drafts,[period.reference]:e.target.value})}/><button className="secondary-button" onClick={()=>publish(period.reference)}>Publikasikan versi</button></details></article>)}</div></div></section></main></>;
}
