import { Form, Head, Link, router } from '@inertiajs/react';
import AppHeader from '../../components/AppHeader';
import { candidateNav } from '../../components/CandidateNav';
type Doc={id:number;type:string;name:string};
type Application={reference:string;job_reference:string;title:string;employer:string;method:string;status:string;submitted_at:string|null;documents:Doc[]};
export default function Applications({applications}:{applications:Application[]}){
 return <><Head title="Lamaran Saya"/><main className="job-page app-surface"><AppHeader context="LAMARAN SAYA" nav={candidateNav('applications')} logout/><section className="job-shell"><header className="event-list-heading"><div><p className="eyebrow">PERJALANAN KARIER</p><h1>Pantau setiap <em>langkah lamaran.</em></h1><p>CV dan dokumen hanya dapat dibuka oleh Anda, perusahaan pemilik lowongan, dan petugas berwenang.</p></div></header><div className="application-list rich">{applications.map(item=><article key={item.reference}><div className="application-main"><small>{item.method.replaceAll('_',' ')}</small><h2><Link href={'/jobs/'+item.job_reference}>{item.title}</Link></h2><p>{item.employer} · {item.submitted_at}</p><div className="document-chips">{item.documents.map(doc=><a key={doc.id} href={'/jobs/applications/'+item.reference+'/documents/'+doc.id}>↗ {doc.type==='cover_letter'?'Cover Letter':doc.name}</a>)}</div></div><b>{item.status.replaceAll('_',' ')}</b>{item.method==='internal'&&<details className="document-upload"><summary>Kelola dokumen privat</summary><Form action={'/jobs/applications/'+item.reference+'/documents'} method="post" encType="multipart/form-data"><label>Jenis<select name="type"><option value="cover_letter">Cover letter</option><option value="supporting_document">Dokumen pendukung</option></select></label><label>PDF/DOC/DOCX<input type="file" name="document" accept=".pdf,.doc,.docx" required/></label><button className="secondary-button">Unggah aman</button></Form></details>}{['submitted','under_review','assessment','interview','offer'].includes(item.status)&&<button className="ghost-button" onClick={()=>router.delete('/jobs/applications/'+item.reference)}>Tarik lamaran</button>}</article>)}</div>{!applications.length&&<div className="ds-empty-state"><span>◎</span><h2>Belum ada lamaran.</h2><p>Temukan lowongan yang cocok lalu kirim CV pilihan Anda.</p><Link className="primary-button" href="/jobs">Jelajahi lowongan</Link></div>}</section></main></>;
}

