import { Head, Link, router, useForm } from '@inertiajs/react';
import AppHeader from '../../components/AppHeader';

type Job = {reference:string;title:string;employer:string;employment_type:string;work_mode:string;city:string|null;expires_at:string|null;application_method:string;source:{type:string;name:string;verified:boolean};tags:string[];possible_duplicate:boolean;bookmarked:boolean};

export default function JobIndex({ jobs, filters }: {jobs:Job[];filters:Record<string,string>}) {
    const search=useForm({q:filters.q||'',city:filters.city||'',work_mode:filters.work_mode||'',employment_type:filters.employment_type||'',tag:filters.tag||''});
    return <><Head title="Lowongan Farmasi"/><main className="job-page app-surface"><AppHeader context="LOWONGAN FARMASI" nav={[{label:'Dashboard',href:'/dashboard'},{label:'Lowongan',href:'/jobs',active:true},{label:'Lamaran Saya',href:'/jobs/applications'},{label:'Undangan',href:'/jobs/invitations'}]} logout/>
    <section className="job-shell"><header className="job-hero"><div><p className="eyebrow">PELUANG YANG TERKURASI</p><h1>Langkah baru untuk<br/><em>karier yang berdampak.</em></h1><p>Temukan peluang farmasi dari perusahaan terverifikasi dan sumber yang ditinjau kampus.</p></div><span className="job-count">{jobs.length}<small>lowongan aktif</small></span></header>
    <form className="job-filter" onSubmit={e=>{e.preventDefault();search.get('/jobs',{preserveState:true})}}><input placeholder="Cari posisi, perusahaan, CPOB, QA/QC..." value={search.data.q} onChange={e=>search.setData('q',e.target.value)}/><input placeholder="Kota" value={search.data.city} onChange={e=>search.setData('city',e.target.value)}/><select value={search.data.work_mode} onChange={e=>search.setData('work_mode',e.target.value)}><option value="">Semua mode</option><option value="onsite">Onsite</option><option value="hybrid">Hybrid</option><option value="remote">Remote</option></select><select value={search.data.employment_type} onChange={e=>search.setData('employment_type',e.target.value)}><option value="">Semua jenis</option><option value="full_time">Penuh waktu</option><option value="part_time">Paruh waktu</option><option value="contract">Kontrak</option><option value="internship">Magang</option><option value="project">Proyek</option></select><button className="primary-button">Cari</button></form>
    <div className="job-grid">{jobs.map(job=><article className="job-card" key={job.reference}><div className="job-card-head"><span>{job.work_mode} · {job.city||'Lokasi fleksibel'}</span><button aria-label="Simpan lowongan" onClick={()=>router.visit(`/jobs/${job.reference}/bookmark`,{method:job.bookmarked?'delete':'post',preserveScroll:true})}>{job.bookmarked?'★':'☆'}</button></div><h2>{job.title}</h2><p className="job-company">{job.employer}</p><div className="topic-row">{job.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="job-source"><b>{job.source.verified?'✓ Terverifikasi':'Sumber tercatat'}</b><small>{job.source.name}</small></div><Link href={`/jobs/${job.reference}`}>Lihat kesempatan →</Link></article>)}</div>
    {jobs.length===0&&<div className="ds-empty-state"><span>⌕</span><h2>Belum ada hasil yang cocok.</h2><p>Coba kata kunci atau lokasi yang lebih luas.</p></div>}</section></main></>;
}
