import { Head, Link, router, useForm } from '@inertiajs/react';
import AppHeader from '../../components/AppHeader';

type Job={reference:string;title:string;employer:string;employment_type:string;work_mode:string;city:string|null;location_text:string|null;expires_at:string|null;description:string;requirements:string|null;responsibilities:string|null;education_requirement:string|null;experience_requirement:string|null;application_method:string;application_instruction:string|null;external_apply_url:string|null;external_apply_email:string|null;source:{type:string;name:string;verified:boolean};tags:string[]};
type Cv={id:number;name:string;template:string|null};
export default function JobShow({job,cvs,application}:{job:Job;cvs:Cv[];application:{status:string;method:string}|null}){
 const form=useForm({cv_id:cvs[0]?.id||0,cover_letter:''});
 const apply=(e:React.FormEvent)=>{e.preventDefault();form.post(`/jobs/${job.reference}/apply`)};
 const external=()=>{router.post(`/jobs/${job.reference}/external-opened`); if(job.external_apply_url) window.open(job.external_apply_url,'_blank','noopener,noreferrer'); if(job.external_apply_email) window.location.href=`mailto:${job.external_apply_email}`};
 return <><Head title={job.title}/><main className="job-page app-surface"><AppHeader context="DETAIL LOWONGAN" nav={[{label:'← Semua lowongan',href:'/jobs'},{label:'Lamaran Saya',href:'/jobs/applications'},{label:'Undangan',href:'/jobs/invitations'}]} logout/><section className="job-shell"><div className="job-detail-layout"><article className="job-detail"><p className="eyebrow">{job.work_mode} · {job.employment_type}</p><h1>{job.title}</h1><h2>{job.employer}</h2><div className="topic-row">{job.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="job-trust"><b>{job.source.verified?'✓ Sumber terverifikasi':'Sumber tercatat'}</b><span>{job.source.name}</span><small>{job.expires_at?`Batas ${job.expires_at}`:'Tanpa tenggat yang dinyatakan'}</small></div><section><h3>Tentang peran</h3><p>{job.description}</p></section>{job.responsibilities&&<section><h3>Tanggung jawab</h3><p>{job.responsibilities}</p></section>}{job.requirements&&<section><h3>Kualifikasi</h3><p>{job.requirements}</p></section>}</article><aside className="job-apply-card"><p className="eyebrow">AJUKAN MINAT</p>{application?<><h2>Lamaran tercatat</h2><p>Status saat ini: <b>{application.status.replaceAll('_',' ')}</b></p><Link className="secondary-button" href="/jobs/applications">Lihat perjalanan lamaran</Link></>:job.application_method==='internal'?<form className="form-stack" onSubmit={apply}><h2>Kirim CV pilihan Anda</h2><p>Salinan CV dikunci saat dikirim agar riwayat lamaran tetap utuh.</p><label>CV<select value={form.data.cv_id} onChange={e=>form.setData('cv_id',Number(e.target.value))}>{cvs.map(cv=><option value={cv.id} key={cv.id}>{cv.name} · {cv.template}</option>)}</select></label><label>Pesan singkat<textarea value={form.data.cover_letter} onChange={e=>form.setData('cover_letter',e.target.value)} rows={5}/></label><button className="primary-button" disabled={!cvs.length||form.processing}>Kirim lamaran</button>{!cvs.length&&<small>Buat CV terlebih dahulu sebelum melamar.</small>}</form>:<><h2>Lamaran melalui sumber eksternal</h2><p>{job.application_instruction||'Ikuti petunjuk pada kanal resmi pemberi kerja.'}</p><button className="primary-button" onClick={external}>Buka kanal lamaran</button><button className="ghost-button" onClick={()=>router.post(`/jobs/${job.reference}/self-report`)}>Saya sudah mengirim di luar SAFA</button><small>Membuka tautan tidak dianggap sebagai lamaran terkirim.</small></>}</aside></div><button className="ghost-button job-report" onClick={()=>router.post(`/jobs/${job.reference}/report`,{reason:'informasi_tidak_akurat'})}>Laporkan lowongan ini</button></section></main></>;
}