import { Head, Link } from '@inertiajs/react';
import AppHeader from '../../components/AppHeader';

export type EventData = { id:number;slug:string;title:string;event_type:string;organizer:string;description:string;starts_at:string;ends_at:string;location_type:string;location_text:string|null;topics:string[];capacity:number|null;registrations_count:number;remaining_capacity:number|null;registered:boolean;registration_id:number|null;registration_open:boolean;registration_state:'open'|'upcoming'|'full'|'closed';registration_opens_at:string|null;registration_closes_at:string|null;registration_notes:string|null;flyer_url:string|null;flyer_alt_text:string };

export default function EventIndex({ events }: { events: EventData[] }) {
    return <><Head title="Event & Seminar" /><main className="event-page app-surface"><AppHeader context="EVENT & PORTOFOLIO" nav={[{label:'Dashboard',href:'/dashboard'},{label:'Jelajahi Event',href:'/events',active:true},{label:'Event Saya',href:'/events/mine'}]} logout />
        <section className="event-shell"><header className="event-hero"><div><p className="eyebrow">TUMBUH LEWAT PENGALAMAN</p><h1>Temukan ruang belajar,<br/><em>bangun jejak profesional.</em></h1><p>Ikuti seminar, pelatihan, dan kegiatan Farmasi UBP. Penyelesaian terverifikasi dapat Anda pilih sebagai bagian CV.</p></div><Link className="secondary-button" href="/events/mine">Lihat event saya</Link></header>
        <div className="event-grid">{events.map(event=><Link className="event-card" href={'/events/'+event.slug} key={event.id}>{event.flyer_url?<img className="event-card-flyer" src={event.flyer_url} alt={event.flyer_alt_text}/>:<div className="event-card-placeholder" aria-hidden="true">✦</div>}<div className="event-card-body"><div className="event-card-top"><span className="event-type">{event.event_type}</span><span>{event.registered?'Terdaftar':event.registration_state==='open'?'Pendaftaran dibuka':event.registration_state==='full'?'Kuota penuh':event.registration_state==='upcoming'?'Segera dibuka':'Ditutup'}</span></div><h2>{event.title}</h2><p>{event.organizer}</p><dl><div><dt>Waktu</dt><dd>{event.starts_at}</dd></div><div><dt>Lokasi</dt><dd>{event.location_text||event.location_type}</dd></div></dl><div className="topic-row">{event.topics.map(topic=><span key={topic}>{topic}</span>)}</div><b>Lihat detail →</b></div></Link>)}</div>
        {events.length===0&&<div className="ds-empty-state"><span>✦</span><h2>Belum ada event aktif.</h2><p>Event yang telah dipublikasikan admin akan tampil di sini.</p></div>}</section></main></>;
}
