import { Head, Link, router, usePage } from '@inertiajs/react';
import AppHeader from '../../components/AppHeader';
import { candidateNav } from '../../components/CandidateNav';
import type { EventData } from './Index';
export default function EventShow({event}:{event:EventData}){
 const page=usePage<{flash?:{success?:string};errors?:Record<string,string>}>().props;
 const actionLabel=event.registration_state==='full'?'Kuota penuh':event.registration_state==='upcoming'?'Pendaftaran belum dibuka':'Pendaftaran ditutup';
 return <><Head title={event.title}/><main className="event-page app-surface"><AppHeader context="DETAIL EVENT" nav={candidateNav('events')} logout/><section className="event-shell event-detail"><Link href="/events">← Kembali ke event</Link>{page.flash?.success&&<div className="alert success">{page.flash.success}</div>}{page.errors?.event&&<div className="alert error">{page.errors.event}</div>}<div className="event-detail-grid"><article className={event.flyer_url?'has-flyer':''}>{event.flyer_url&&<img className="event-detail-flyer" src={event.flyer_url} alt={event.flyer_alt_text}/>}<div className="event-detail-copy"><div className="event-card-top"><span className="event-type">{event.event_type}</span><span>{event.location_type}</span></div><p className="eyebrow">FARMASI UBP · EVENT</p><h1>{event.title}</h1><p className="event-lead">{event.description}</p><div className="topic-row">{event.topics.map(t=><span key={t}>{t}</span>)}</div></div></article><aside><h2>Informasi kegiatan</h2><dl><div><dt>Penyelenggara</dt><dd>{event.organizer}</dd></div><div><dt>Mulai</dt><dd>{event.starts_at}</dd></div><div><dt>Selesai</dt><dd>{event.ends_at}</dd></div><div><dt>Lokasi</dt><dd>{event.location_text||event.location_type}</dd></div><div><dt>Peserta</dt><dd>{event.registrations_count}{event.capacity?' / '+event.capacity:''}</dd></div>{event.remaining_capacity!==null&&<div><dt>Sisa kuota</dt><dd>{event.remaining_capacity}</dd></div>}{event.registration_opens_at&&<div><dt>Pendaftaran</dt><dd>{event.registration_opens_at}—{event.registration_closes_at||'menjelang acara'}</dd></div>}</dl>{event.registration_notes&&<div className="event-registration-notes"><strong>Sebelum mendaftar</strong><p>{event.registration_notes}</p></div>}{event.registered?<><span className="success-badge">✓ Anda terdaftar</span><Link className="secondary-button" href="/events/mine">Lihat status keikutsertaan</Link><button className="ghost-button" onClick={()=>router.delete('/events/'+event.slug+'/registrations/'+event.registration_id)}>Batalkan pendaftaran</button></>:<button className="primary-button" disabled={!event.registration_open} onClick={()=>router.post('/events/'+event.slug+'/registrations')}>{event.registration_open?'Daftar sekarang':actionLabel}</button>}</aside></div></section></main></>;
}
