import { Head, Link, useForm } from '@inertiajs/react';
import type { TemplateConfiguration } from './CvPaper';
import AppHeader from '../../components/AppHeader';
import { candidateNav } from '../../components/CandidateNav';

type Item = { source_item_id: number; label: string; enabled: boolean; sort_order: number };
type Section = { key: string; label: string; enabled: boolean; sort_order: number; display_title: string | null; items: Item[] };
type VisibleField = { key: string; label: string; enabled: boolean };
type Template = { version_id: number; key: string; name: string; description: string; version: string; configuration: TemplateConfiguration };
type Existing = { id: number; name: string; template_version_id: number; custom_headline: string | null; custom_summary: string | null; status: 'draft' | 'active' } | null;

export default function CvEditor({ mode, cv, templates, profile, sections, visibleFields }: { mode: 'create' | 'edit'; cv: Existing; templates: Template[]; profile: { headline: string | null; summary: string | null }; sections: Section[]; visibleFields: VisibleField[] }) {
    const fieldVisibility = Object.fromEntries(visibleFields.map(field => [field.key, field.enabled])) as Record<string, boolean>;
    const form = useForm({ name: cv?.name ?? 'CV Profesional', template_version_id: cv?.template_version_id ?? templates[0]?.version_id ?? 0, custom_headline: cv?.custom_headline ?? '', custom_summary: cv?.custom_summary ?? '', field_visibility: fieldVisibility, status: cv?.status ?? 'draft', sections });
    const setSection = (index: number, change: Partial<Section>) => form.setData('sections', form.data.sections.map((section, itemIndex) => itemIndex === index ? { ...section, ...change } : section));
    const moveSection = (index: number, delta: number) => { const next = [...form.data.sections]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; form.setData('sections', next.map((section, order) => ({ ...section, sort_order: order }))); };
    const setItem = (sectionIndex: number, itemIndex: number, enabled: boolean) => setSection(sectionIndex, { items: form.data.sections[sectionIndex].items.map((item, index) => index === itemIndex ? { ...item, enabled } : item) });
    const moveItem = (sectionIndex: number, itemIndex: number, delta: number) => { const items = [...form.data.sections[sectionIndex].items]; const target = itemIndex + delta; if (target < 0 || target >= items.length) return; [items[itemIndex], items[target]] = [items[target], items[itemIndex]]; setSection(sectionIndex, { items: items.map((item, order) => ({ ...item, sort_order: order })) }); };
    const submit = () => cv ? form.put(`/cv/${cv.id}`) : form.post('/cv');

    return <><Head title={cv ? 'Edit CV' : 'Buat CV'} /><main className="cv-page cv-editor-page"><AppHeader context="EDITOR CV" nav={candidateNav('cv')} logout /><section className="cv-shell cv-editor-shell"><div className="cv-editor-intro"><p className="eyebrow">{mode === 'create' ? 'CV BARU' : 'PERBARUI CV'}</p><h1 className="page-title">Tampilkan yang paling<br /><em>berarti untuk tujuan Anda.</em></h1><p className="page-lead">Pilih tampilan, atur informasi, lalu susun cerita profesional yang ringkas dan meyakinkan. Profil utama Anda tetap aman.</p></div>
        <form onSubmit={event => { event.preventDefault(); submit(); }} className="cv-editor-form">
            <section className="profile-form-card editor-block"><div className="editor-block-heading"><span>01</span><div><h2>Identitas CV</h2><p>Beri nama internal dan sesuaikan pesan utama untuk peluang ini.</p></div></div><div className="form-grid"><label>Nama CV<input value={form.data.name} onChange={event => form.setData('name', event.target.value)} required /></label><label>Status<select value={form.data.status} onChange={event => form.setData('status', event.target.value as 'draft' | 'active')}><option value="draft">Draf</option><option value="active">Aktif</option></select></label><label className="form-wide">Headline khusus<input value={form.data.custom_headline} onChange={event => form.setData('custom_headline', event.target.value)} placeholder={profile.headline || 'Contoh: Apoteker yang teliti dan berorientasi pada pasien'} /></label><label className="form-wide">Ringkasan khusus<textarea value={form.data.custom_summary} onChange={event => form.setData('custom_summary', event.target.value)} placeholder={profile.summary || 'Tulis ringkasan khusus untuk tujuan CV ini'} /></label></div></section>
            <section className="profile-form-card editor-block"><div className="editor-block-heading"><span>02</span><div><h2>Pilih karakter visual</h2><p>Pilih gaya profesional yang sesuai. Pergantian template tidak mengubah isi maupun pilihan Anda.</p></div></div><div className="template-picker">{templates.map(template => <label className={`template-option ${form.data.template_version_id === template.version_id ? 'selected' : ''}`} key={template.version_id}><input type="radio" name="template" checked={form.data.template_version_id === template.version_id} onChange={() => form.setData('template_version_id', template.version_id)} /><span className={`template-thumb ${template.key} thumb-${template.configuration.layout}`}><i /><b /><em /></span><span><strong>{template.name}</strong><small>{template.description}</small><small>Versi {template.version}</small></span>{form.data.template_version_id === template.version_id && <b className="template-current">Dipilih</b>}</label>)}</div></section>
            <section className="profile-form-card editor-block"><div className="editor-block-heading"><span>03</span><div><h2>Kontak dan identitas</h2><p>Sembunyikan informasi tertentu khusus untuk CV ini.</p></div></div><div className="cv-field-grid">{visibleFields.map(field => <label className={`visibility-card ${form.data.field_visibility[field.key] ? 'is-visible' : ''}`} key={field.key}><input type="checkbox" checked={form.data.field_visibility[field.key]} onChange={event => form.setData('field_visibility', { ...form.data.field_visibility, [field.key]: event.target.checked })} /><span><strong>{field.label}</strong><small>{form.data.field_visibility[field.key] ? 'Ditampilkan' : 'Disembunyikan'}</small></span><i aria-hidden="true" /></label>)}</div></section>
            <section className="profile-form-card editor-block"><div className="editor-block-heading"><span>04</span><div><h2>Bagian dan urutan</h2><p>Aktifkan bagian yang relevan, pilih item, dan atur urutannya.</p></div></div><div className="cv-section-editor">{form.data.sections.map((section, index) => <article className={section.enabled ? 'section-enabled' : 'section-hidden'} key={section.key}><div className="cv-section-control"><label className="visibility-toggle"><input type="checkbox" checked={section.enabled} onChange={event => setSection(index, { enabled: event.target.checked })} /><i aria-hidden="true" /><span><strong>{section.label}</strong><small>{section.enabled ? `${section.items.filter(item => item.enabled).length || (section.key === 'summary' ? 1 : 0)} item ditampilkan` : 'Bagian disembunyikan'}</small></span></label><span className="cv-order-buttons"><button type="button" aria-label={`Naikkan ${section.label}`} onClick={() => moveSection(index, -1)} disabled={index === 0}>↑</button><button type="button" aria-label={`Turunkan ${section.label}`} onClick={() => moveSection(index, 1)} disabled={index === form.data.sections.length - 1}>↓</button></span></div><input aria-label={`Judul tampilan ${section.label}`} value={section.display_title ?? ''} onChange={event => setSection(index, { display_title: event.target.value })} placeholder={`Judul tampilan: ${section.label}`} />{section.items.length > 0 && <div className="cv-item-list">{section.items.map((item, itemIndex) => <div className={item.enabled ? 'cv-item-row is-visible' : 'cv-item-row'} key={item.source_item_id}><label className="check-row"><input type="checkbox" checked={item.enabled} onChange={event => setItem(index, itemIndex, event.target.checked)} /><span>{item.label}</span><small>{item.enabled ? 'Tampil' : 'Hidden'}</small></label><span className="cv-order-buttons"><button type="button" aria-label={`Naikkan ${item.label}`} onClick={() => moveItem(index, itemIndex, -1)} disabled={itemIndex === 0}>↑</button><button type="button" aria-label={`Turunkan ${item.label}`} onClick={() => moveItem(index, itemIndex, 1)} disabled={itemIndex === section.items.length - 1}>↓</button></span></div>)}</div>}</article>)}</div></section>
            {Object.keys(form.errors).length > 0 && <div className="alert error">Periksa kembali pilihan Anda. Semua bagian harus memiliki konfigurasi yang valid.</div>}<div className="form-actions cv-editor-actions"><button className="primary-button" disabled={form.processing}>{form.processing ? 'Menyimpan…' : 'Simpan dan lihat preview'}</button><Link className="secondary-button" href="/cv">Batal</Link><span>Perubahan tampilan belum mengubah versi publik sampai Publish Update.</span></div>
        </form></section></main></>;
}
