import { type FormEvent, useState } from 'react';
import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import CvPaper, { type CvPaperData } from './CvPaper';
import WebPortfolio from './WebPortfolio';

type PreviewCv = CvPaperData & { id: number; name: string };
type Publishing = { published: boolean; revision_number: number | null; published_at: string | null; has_unpublished_changes: boolean };
type ShareLink = { id: string; label: string | null; active: boolean; expires_at: string | null; allow_pdf_download: boolean; follow_latest_published: boolean; revision_number: number | null; view_count: number; last_viewed_at: string | null; url: string | null; token_available: boolean };

export default function CvPreview({ cv, publishing, shareLinks }: { cv: PreviewCv; publishing: Publishing; shareLinks: ShareLink[] }) {
    const flash = usePage<{ flash?: { success?: string } }>().props.flash;
    const [showShare, setShowShare] = useState(false);
    const form = useForm({ label: '', expires_at: '', allow_pdf_download: true, follow_latest_published: true });
    const submitShare = (event: FormEvent) => { event.preventDefault(); form.post(`/cv/${cv.id}/shares`, { onSuccess: () => form.reset() }); };
    const copy = async (url: string) => { await navigator.clipboard.writeText(url); };

    return <><Head title={`Preview ${cv.name}`} /><main className="cv-preview-page"><header className="compact-header print-hidden"><Link className="brand" href="/cv"><span className="brand-mark">SK</span><span><strong>SAFA KARIR</strong><small>PREVIEW PRIVAT</small></span></Link><div className="header-actions"><Link className="secondary-button" href={`/cv/${cv.id}/edit`}>Edit CV</Link><Link className="text-link" href="/cv">Semua CV</Link></div></header>
        <div className="preview-toolbar print-hidden"><div><strong>{cv.name}</strong><span>{cv.template.name} · versi {cv.template.version}</span>{publishing.has_unpublished_changes ? <span className="unpublished-badge">Perubahan belum dipublikasikan</span> : publishing.published && <span className="published-badge">Versi publik sudah sesuai</span>}</div><div className="export-actions"><button className="toolbar-primary" onClick={() => router.post(`/cv/${cv.id}/publish`)}>{publishing.published ? 'Publish Update' : 'Publish'}</button><a href={`/cv/${cv.id}/download.pdf`}>Unduh PDF</a><a href={`/cv/${cv.id}/download.docx`}>Unduh DOCX</a><button onClick={() => window.print()}>Cetak</button><button onClick={() => publishing.published ? setShowShare(!showShare) : alert('Publish CV terlebih dahulu.')}>Atur share</button></div></div>
        {flash?.success && <div className="alert success share-alert print-hidden">{flash.success}</div>}
        {publishing.published && <p className="publish-meta print-hidden">Revision publik {publishing.revision_number} · diterbitkan {new Date(publishing.published_at!).toLocaleString('id-ID')}</p>}
        {showShare && publishing.published && <section className="share-manager print-hidden"><div className="share-manager-heading"><div><p className="eyebrow">KONTROL SHARE</p><h2>Bagikan karya terbaik Anda.</h2><p>Buat tautan khusus, tentukan masa aktif, dan kendalikan izin unduh PDF.</p></div></div>
            <form onSubmit={submitShare} className="share-create"><label>Label<input value={form.data.label} onChange={e => form.setData('label', e.target.value)} placeholder="Contoh: Lamaran Rumah Sakit" /></label><label>Kedaluwarsa<input type="datetime-local" value={form.data.expires_at} onChange={e => form.setData('expires_at', e.target.value)} /></label><label className="check-row"><input type="checkbox" checked={form.data.allow_pdf_download} onChange={e => form.setData('allow_pdf_download', e.target.checked)} /> Izinkan PDF publik</label><label className="check-row"><input type="checkbox" checked={form.data.follow_latest_published} onChange={e => form.setData('follow_latest_published', e.target.checked)} /> Ikuti Publish Update</label><button className="primary-button" disabled={form.processing}>Buat tautan</button></form>
            <div className="share-list">{shareLinks.length === 0 && <p>Belum ada tautan. Draft tidak akan diterbitkan diam-diam.</p>}{shareLinks.map(link => <article key={link.id}><div><span className={`share-status ${link.active ? 'active' : ''}`}>{link.active ? 'Aktif' : 'Nonaktif'}</span><h3>{link.label || 'Tautan CV'}</h3><p>Revision {link.revision_number ?? '-'} · {link.view_count} tayangan · PDF {link.allow_pdf_download ? 'diizinkan' : 'dinonaktifkan'}</p>{!link.token_available && <small>Tautan lama tidak bisa dibaca. Gunakan Rotate untuk membuat token baru.</small>}{link.expires_at && <small>Kedaluwarsa {new Date(link.expires_at).toLocaleString('id-ID')}</small>}</div><div className="share-actions">{link.url && <><button onClick={() => copy(link.url!)}>Copy Link</button><a href={link.url} target="_blank" rel="noreferrer">Open</a></>}<button onClick={() => router.put(`/cv/${cv.id}/shares/${link.id}`, { allow_pdf_download: !link.allow_pdf_download })}>{link.allow_pdf_download ? 'Matikan PDF' : 'Izinkan PDF'}</button><button onClick={() => confirm('Token lama langsung tidak berlaku. Putar token?') && router.post(`/cv/${cv.id}/shares/${link.id}/rotate`)}>Rotate</button>{link.active && <button className="danger-text" onClick={() => confirm('Nonaktifkan tautan ini?') && router.delete(`/cv/${cv.id}/shares/${link.id}`)}>Disable</button>}</div></article>)}</div>
        </section>}
        {cv.template.key === 'cv-09' ? <WebPortfolio cv={cv} actions={{ pdfUrl: `/cv/${cv.id}/download.pdf`, onShare: () => publishing.published ? setShowShare(true) : alert('Publish CV terlebih dahulu.'), onPrint: () => window.print() }} /> : <CvPaper cv={cv} />}<p className="preview-note print-hidden">Preview privat. Tautan publik hanya berubah setelah Anda memilih Publish atau Publish Update.</p></main></>;
}

